<div class="block-container">
    <div class="block-links">
        <h3>Containers</h3>
            <ul>

            </ul>
    </div> 
<p>&nbsp;</p>
</div>     
                                                                                                                                                                                                                                <div                                                      <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/caution-danger/id/22/">Caution/Danger</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/safety-rules-age-restrictions/id/23/">Safety Rules/Age Restrictions</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/voltage-decals/id/24/">Voltage Decals</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/hazardous-waste/id/25/">Hazardous Waste</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/misc/id/26/">Misc</a></li>
                                                                </ul>
                            </div>      
                                                                                            <div class="block-links">
                <h3>Recycling</h3>
                                                        <ul>
                                                                                                                        <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/single-stream-commingled/id/28/">Single Stream/Commingled</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/multi-message-instructions/id/29/">Multi Message/Instructions</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/english-spanish/id/30/">English/Spanish</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/single-message/id/31/">Single Message</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/recycling-arrows/id/32/">Recycling Arrows</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/misc/id/33/">Misc</a></li>
                                                                </ul>
                            </div>      
                                                                                                        <div class="block-links">
                <h3>Truck Safety</h3>
                                                        <ul>
                                                                                                                        <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/truck-rear-caution/id/43/">Truck Rear Caution</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/lockout-tagout/id/44/">Lockout/Tagout</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/conspicuity/id/45/">Conspicuity</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/driver-helper-safety/id/46/">Driver/Helper Safety</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/numbers/id/47/">Numbers</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/misc/id/48/">Misc</a></li>
                                                                </ul>
                            </div>      
                                                                                                        <div class="block-links">
                <h3>Facility Safety</h3>
                                                        <ul>
                                                                                                                        <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/shop-safety/id/50/">Shop Safety</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/parking-signs/id/53/">Parking Signs</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/landfill-safety/id/54/">Landfill Safety</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/misc/id/55/">Misc</a></li>
                                                                </ul>
                            </div>      
                                                                                                        <div class="block-links">
                <h3>Portable Restroom</h3>
                                                        <ul>
                                                                                                                        <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/service-date-records/id/58/">Service Date Records</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/men-women/id/59/">Men/Women</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/notice-instruction/id/60/">Notice/Instruction</a></li>
                                                                </ul>
                            </div>      
                                                                    <div class="block-links">
                <h3>Spanish</h3>
                                                        <ul>
                                                                                                                        <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/container-compactor/id/63/">Container/Compactor</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/recycling/id/64/">Recycling</a></li>
                                                                                                                                                <li><a href="http://127.0.0.1/wastegraphicsCE/catalog/category/view/s/safety/id/65/">Safety</a></li>
                                                                </ul>
                            </div>      
                                                </div>